/**
 * AIFlow Spec Writer — B5.2 UI page.
 *
 * Lets the user describe a feature/API/DB/user story in plain text and
 * get back a Markdown specification generated by the spec_writer skill
 * (analyze -> select template -> generate -> review -> finalize).
 */

import { useState } from "react";
import { useTranslate } from "../lib/i18n";
import { useApi } from "../lib/hooks";
import { fetchApi } from "../lib/api-client";
import { PageLayout } from "../layout/PageLayout";
import { ErrorState } from "../components-new/ErrorState";
import { DataTable, type Column } from "../components-new/DataTable";

type SpecType = "feature" | "api" | "db" | "user_story";
type Lang = "hu" | "en";

interface SpecRecord {
  id: string;
  title: string;
  spec_type: string;
  language: string;
  markdown_content: string;
  score: number;
  is_acceptable: boolean;
  sections_count: number;
  word_count: number;
  created_at: string;
  source: string;
}

interface SpecListResponse {
  specs: SpecRecord[];
  total: number;
  source: string;
}

interface WriteSpecResponse extends SpecRecord {
  requirement?: Record<string, unknown> | null;
  review?: {
    score: number;
    is_acceptable: boolean;
    missing_sections: string[];
    questions: string[];
    suggestions: string[];
  } | null;
}

export function SpecWriter() {
  const translate = useTranslate();
  const [rawText, setRawText] = useState("");
  const [specType, setSpecType] = useState<SpecType>("feature");
  const [language, setLanguage] = useState<Lang>("hu");
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<WriteSpecResponse | null>(null);
  const [err, setErr] = useState<string | null>(null);

  const { data, loading, error, refetch } =
    useApi<SpecListResponse>("/api/v1/specs");

  const handleWrite = async () => {
    if (!rawText.trim()) return;
    setBusy(true);
    setErr(null);
    try {
      const resp = await fetchApi<WriteSpecResponse>(
        "POST",
        "/api/v1/specs/write",
        {
          raw_text: rawText,
          spec_type: specType,
          language,
        },
      );
      setResult(resp);
      refetch();
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Spec generation failed");
    } finally {
      setBusy(false);
    }
  };

  const handleDownload = () => {
    if (!result) return;
    const blob = new Blob([result.markdown_content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${result.title.replace(/\s+/g, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const columns: Column<Record<string, unknown>>[] = [
    {
      key: "title",
      label: translate("aiflow.specWriter.colTitle"),
      render: (item) => (
        <span className="font-medium text-gray-800 dark:text-gray-200">
          {String(item.title || "(untitled)")}
        </span>
      ),
    },
    {
      key: "spec_type",
      label: translate("aiflow.specWriter.colType"),
      render: (item) => (
        <span className="rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-700 dark:bg-gray-800 dark:text-gray-300">
          {String(item.spec_type)}
        </span>
      ),
    },
    {
      key: "language",
      label: translate("aiflow.specWriter.colLanguage"),
      render: (item) => (
        <span className="text-xs text-gray-500">
          {String(item.language).toUpperCase()}
        </span>
      ),
    },
    {
      key: "score",
      label: translate("aiflow.specWriter.colScore"),
      getValue: (item) => Number(item.score ?? 0),
      render: (item) => {
        const s = Number(item.score ?? 0);
        const ok = Boolean(item.is_acceptable);
        return (
          <span
            className={`font-medium ${ok ? "text-green-600" : "text-amber-600"}`}
          >
            {s ? `${s.toFixed(1)}/10` : "—"}
          </span>
        );
      },
    },
    {
      key: "sections_count",
      label: translate("aiflow.specWriter.colSections"),
      render: (item) => (
        <span className="text-xs text-gray-500">
          {String(item.sections_count ?? 0)}
        </span>
      ),
    },
    {
      key: "created_at",
      label: translate("aiflow.specWriter.colCreated"),
      render: (item) => (
        <span className="text-xs text-gray-500">
          {new Date(String(item.created_at)).toLocaleString()}
        </span>
      ),
    },
  ];

  return (
    <PageLayout titleKey="aiflow.specWriter.title" source={data?.source}>
      <div className="mb-6 grid grid-cols-1 gap-4 lg:grid-cols-2">
        {/* Input card */}
        <div className="rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
          <p className="mb-2 text-sm font-medium text-gray-700 dark:text-gray-300">
            {translate("aiflow.specWriter.inputLabel")}
          </p>
          <textarea
            value={rawText}
            onChange={(e) => setRawText(e.target.value)}
            rows={8}
            placeholder={translate("aiflow.specWriter.placeholder")}
            className="w-full rounded-lg border border-gray-300 bg-white p-3 text-sm text-gray-700 placeholder-gray-400 focus:border-brand-500 focus:outline-none dark:border-gray-600 dark:bg-gray-800 dark:text-gray-200"
          />

          <div className="mt-3 grid grid-cols-2 gap-3">
            <div>
              <label className="mb-1 block text-xs font-medium text-gray-600 dark:text-gray-400">
                {translate("aiflow.specWriter.specType")}
              </label>
              <select
                value={specType}
                onChange={(e) => setSpecType(e.target.value as SpecType)}
                className="w-full rounded-lg border border-gray-300 bg-white px-2 py-1.5 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-gray-200"
              >
                <option value="feature">feature</option>
                <option value="api">api</option>
                <option value="db">db</option>
                <option value="user_story">user_story</option>
              </select>
            </div>
            <div>
              <label className="mb-1 block text-xs font-medium text-gray-600 dark:text-gray-400">
                {translate("aiflow.specWriter.language")}
              </label>
              <select
                value={language}
                onChange={(e) => setLanguage(e.target.value as Lang)}
                className="w-full rounded-lg border border-gray-300 bg-white px-2 py-1.5 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-gray-200"
              >
                <option value="hu">Magyar</option>
                <option value="en">English</option>
              </select>
            </div>
          </div>

          <button
            onClick={handleWrite}
            disabled={busy || !rawText.trim()}
            className="mt-3 w-full rounded-lg bg-brand-500 py-2 text-sm font-semibold text-white hover:bg-brand-600 disabled:opacity-50"
          >
            {busy
              ? translate("aiflow.common.loading")
              : translate("aiflow.specWriter.write")}
          </button>
          {err && <p className="mt-2 text-xs text-red-600">{err}</p>}
        </div>

        {/* Output card */}
        <div className="rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
          <div className="mb-2 flex items-center justify-between">
            <p className="text-sm font-medium text-gray-700 dark:text-gray-300">
              {translate("aiflow.specWriter.outputLabel")}
            </p>
            {result && (
              <button
                onClick={handleDownload}
                className="rounded-md border border-gray-300 px-2 py-1 text-xs text-gray-600 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-400"
              >
                {translate("aiflow.specWriter.download")}
              </button>
            )}
          </div>

          <div className="min-h-48 overflow-auto rounded-lg bg-gray-50 p-3 text-xs text-gray-700 dark:bg-gray-800 dark:text-gray-300">
            {result ? (
              <>
                <div className="mb-2 flex items-center gap-2">
                  <span
                    className={`rounded px-2 py-0.5 text-xs font-medium ${
                      result.is_acceptable
                        ? "bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300"
                        : "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300"
                    }`}
                  >
                    {result.score.toFixed(1)}/10 ·{" "}
                    {result.is_acceptable
                      ? translate("aiflow.specWriter.accepted")
                      : translate("aiflow.specWriter.needsWork")}
                  </span>
                  <span className="text-xs text-gray-500">
                    {result.sections_count} sections · {result.word_count} words
                  </span>
                </div>
                <pre className="whitespace-pre-wrap font-mono text-[11px] leading-relaxed">
                  {result.markdown_content}
                </pre>
                {result.review?.suggestions &&
                  result.review.suggestions.length > 0 && (
                    <div className="mt-3 border-t border-gray-200 pt-2 dark:border-gray-700">
                      <p className="mb-1 text-xs font-medium text-gray-600 dark:text-gray-400">
                        {translate("aiflow.specWriter.suggestions")}
                      </p>
                      <ul className="ml-4 list-disc text-xs">
                        {result.review.suggestions.map((s, i) => (
                          <li key={i}>{s}</li>
                        ))}
                      </ul>
                    </div>
                  )}
              </>
            ) : (
              <span className="text-gray-400">
                {translate("aiflow.specWriter.outputPlaceholder")}
              </span>
            )}
          </div>
        </div>
      </div>

      <h3 className="mb-2 text-base font-semibold text-gray-900 dark:text-gray-100">
        {translate("aiflow.specWriter.savedSpecs")}
      </h3>
      {error ? (
        <ErrorState error={error} onRetry={refetch} />
      ) : (
        <DataTable
          data={(data?.specs ?? []) as unknown as Record<string, unknown>[]}
          columns={columns}
          loading={loading}
          searchKeys={["title", "spec_type", "language"]}
        />
      )}
    </PageLayout>
  );
}
