"""Measure flag-ON attachment-feature extraction cost (Sprint O / S127).

Manual one-shot helper — NOT in CI. Iterates the 25 Sprint O fixture emails,
unpacks their attachments, and runs ``_maybe_extract_attachment_features``
(the same code path the orchestrator hits when
``AIFLOW_UC3_ATTACHMENT_INTENT__ENABLED=true``) against each. Writes
``docs/uc3_attachment_extract_timing.md`` with per-email + aggregate
wall-clock + the extracted feature payload.

Usage::

    .venv/Scripts/python.exe scripts/measure_uc3_attachment_extract_cost.py

STOP condition (HARD): aggregate wall-clock > 120 seconds — exits 2 so the
session can halt and rescope the per-email budget with the user (plan §5
HARD STOP #2).
"""

from __future__ import annotations

import asyncio
import statistics
import sys
import time
from email import message_from_bytes
from email.message import Message
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any
from uuid import uuid4

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(REPO_ROOT))

from aiflow.core.config import UC3AttachmentIntentSettings  # noqa: E402
from aiflow.intake.package import IntakeFile  # noqa: E402
from aiflow.services.email_connector.orchestrator import (  # noqa: E402
    _maybe_extract_attachment_features,
)

FIXTURE_DIR = REPO_ROOT / "data" / "fixtures" / "emails_sprint_o"
MANIFEST_PATH = FIXTURE_DIR / "manifest.yaml"
REPORT_PATH = REPO_ROOT / "docs" / "uc3_attachment_extract_timing.md"

HALT_WALL_CLOCK_SECONDS = 120.0


def _explode_attachments(raw: bytes, target_dir: Path) -> list[IntakeFile]:
    """Drop each .eml part into target_dir and return matching IntakeFile entries.

    Skips the body-only marker ``note.txt`` that fixtures attach to satisfy
    the intake CHECK constraint.
    """
    msg: Message = message_from_bytes(raw)
    target_dir.mkdir(parents=True, exist_ok=True)
    files: list[IntakeFile] = []
    for part in msg.walk():
        if part.is_multipart():
            continue
        filename = part.get_filename()
        if not filename or filename == "note.txt":
            continue
        payload = part.get_payload(decode=True) or b""
        path = target_dir / filename
        path.write_bytes(payload)
        files.append(
            IntakeFile(
                file_path=str(path),
                file_name=filename,
                mime_type=part.get_content_type(),
                size_bytes=len(payload),
                sha256="0" * 64,
            )
        )
    return files


async def _measure_one(
    fixture_id: str,
    raw: bytes,
    settings: UC3AttachmentIntentSettings,
    workdir: Path,
) -> dict[str, Any]:
    files = _explode_attachments(raw, workdir / fixture_id)
    start = time.perf_counter()
    features = await _maybe_extract_attachment_features(files, settings=settings)
    elapsed_ms = (time.perf_counter() - start) * 1000.0
    return {
        "id": fixture_id,
        "attachment_count": len(files),
        "elapsed_ms": round(elapsed_ms, 2),
        "features": features,
    }


async def measure() -> dict[str, Any]:
    manifest = yaml.safe_load(MANIFEST_PATH.read_text(encoding="utf-8"))
    fixtures: list[dict[str, Any]] = manifest["fixtures"]
    settings = UC3AttachmentIntentSettings(
        enabled=True,
        max_attachment_mb=10,
        total_budget_seconds=30.0,
    )
    rows: list[dict[str, Any]] = []
    wall_start = time.perf_counter()
    with TemporaryDirectory(prefix=f"uc3_extract_{uuid4().hex[:6]}_") as tmp:
        workdir = Path(tmp)
        for entry in fixtures:
            eml = (FIXTURE_DIR / f"{entry['id']}.eml").read_bytes()
            row = await _measure_one(entry["id"], eml, settings, workdir)
            row["cohort"] = entry["cohort"]
            row["expected_intent"] = entry["expected_intent"]
            rows.append(row)
    wall_ms = (time.perf_counter() - wall_start) * 1000.0

    latencies = [r["elapsed_ms"] for r in rows]
    p50 = statistics.median(latencies) if latencies else 0.0
    p95 = (
        statistics.quantiles(latencies, n=20)[18]
        if len(latencies) >= 20
        else (max(latencies) if latencies else 0.0)
    )
    return {
        "rows": rows,
        "wall_clock_ms": round(wall_ms, 2),
        "p50_ms": round(p50, 2),
        "p95_ms": round(p95, 2),
        "n": len(rows),
    }


def _render_report(result: dict[str, Any]) -> str:
    rows = result["rows"]
    lines: list[str] = []
    lines.append("# UC3 Sprint O — Attachment Feature Extraction Timing")
    lines.append("")
    lines.append(
        "> Generated by `scripts/measure_uc3_attachment_extract_cost.py`. "
        "Manual one-shot — NOT in CI."
    )
    lines.append(
        "> Path under test: orchestrator helper "
        "`_maybe_extract_attachment_features` with "
        "`AIFLOW_UC3_ATTACHMENT_INTENT__ENABLED=true` semantics."
    )
    lines.append("")
    lines.append("## Headline")
    lines.append("")
    lines.append(f"- **Wall clock:** {result['wall_clock_ms']:.0f} ms ({result['n']} fixtures)")
    lines.append(f"- **p50 per-email:** {result['p50_ms']:.0f} ms")
    lines.append(f"- **p95 per-email:** {result['p95_ms']:.0f} ms")
    halt = HALT_WALL_CLOCK_SECONDS * 1000.0
    pass_str = "PASS" if result["wall_clock_ms"] < halt else "FAIL (HALT)"
    lines.append(f"- **Budget gate (< {HALT_WALL_CLOCK_SECONDS:.0f} s wall clock):** {pass_str}")
    lines.append("")
    lines.append("## Per-fixture")
    lines.append("")
    lines.append("| Fixture | Cohort | Attachments | Latency (ms) | invoice# | total$ | mime |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in rows:
        # S128: helper now wraps features under "attachment_features" alongside
        # "attachment_text_preview"; unwrap defensively for the timing rows.
        payload = r.get("features") or {}
        f = payload.get("attachment_features") if isinstance(payload, dict) else None
        f = f or {}
        lines.append(
            f"| `{r['id']}` | {r['cohort']} | {r['attachment_count']} | "
            f"{r['elapsed_ms']:.0f} | "
            f"{f.get('invoice_number_detected', '—')} | "
            f"{f.get('total_value_detected', '—')} | "
            f"{f.get('mime_profile', '—')} |"
        )
    lines.append("")
    return "\n".join(lines)


async def main() -> int:
    result = await measure()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(_render_report(result), encoding="utf-8")
    print(f"[ok] wrote {REPORT_PATH.relative_to(REPO_ROOT)}")
    print(
        f"[stats] wall={result['wall_clock_ms']:.0f}ms "
        f"p50={result['p50_ms']:.0f}ms p95={result['p95_ms']:.0f}ms n={result['n']}"
    )
    if result["wall_clock_ms"] > HALT_WALL_CLOCK_SECONDS * 1000.0:
        print(
            f"[HALT] wall clock {result['wall_clock_ms']:.0f}ms "
            f"exceeds {HALT_WALL_CLOCK_SECONDS:.0f}s budget — STOP per plan §5",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
